import { gql } from "apollo-boost";

/**
 * This is an exmaple of a shared query. We don't need to define these in
 * components, obviously. And the types directory that is generated by our
 * apollo script is available next to it as well.
 *
 * Reminder of that script:
 * `yarn run apollo codegen:generate --localSchemaFile=graphql-schema.json\
 * --target=typescript --tagName=gql --addTypename\
 * --globalTypesFile=src/types/graphql-global-types.ts types`
 */
export const GET_REPOSITORY = gql`
  query getRepository($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
      id
    }
  }
`
